branches:
  only:
  - "/^v[0-9]/"
env:
  global:
  - secure: lxKGimckM+oOMvQeRVzhJW8pOTGXWqydsLng1Yjki3rutN0R4IzJlNO+AfEUmdKkH1qWoW+p81F2gNLCk50D890pbMJXDQhqM8dPW8uJ5cIXVDHTLgSfQ7HrxjJOy+zaLcxKNz7JJ33MWDWFXEZCwWKedzNJdVWPKb6Tbyl/HaCbr7E2Vvou+iVexeWHnG5cjiPLNSF4g4Wd07ACJ32AEjNRWbeB349+aOJFZZ42x/C6LyvLSrEoOwZkj40dny+izabdtbXrj3Oeebogl6ku9RPNiZYVHrVL+pD0T7UjN7AuRfVtS5vxhsQe+74f9w9LUnl+5xRxB/3RGgLYz4naNUBQxE4tNgkAgwyugyIpcgjPQ4IgERHnS9cF0UXmjAqRfTeqp2MP/tAnhXKjykPAi+jmJ9WS+KSsflAiUTzHYIrZ7cyf0yWXjUKxoupyj8kYpa/+MKPD0oTXx1xQfjV5r+WIx98WasoVC8z5oVtlLUlHJU3we203440gaZ2dGmlQKPcq4Wzx8lVXtP+As0W8Ye4ASb9NZVwEY3Alu0/KND167W0DtMzVgWw0DZS6Fu7Qmn7hdBtmmM10ohuzw9MuFLVPPbWLQxcZDto2x13dwTsY2XLCa4vjOlH5roukUnz3Cl78148QWNXFwcU2BerDRsvU2QS5pe4GpHMxmykDzYs=
  - secure: HXVgFxfsU/xYOhszh9yYQlteGi/wguiKaAIvv6IEMGp6Cb4EF3TkKq+JA3nC0sLzmHsCA3idG9DBUsJnqyRnlDg9lpeMoQUvgdDflQPgzKXptyKhwMyaa8ERdVjCmWXJPOIkQLK9eGNZ4os998jgmHXSI0genVrgmlTdK+HFQ/HDB5kIcjdQckxG/NGhvG7SQc/peewwuueWQWZLSKfz9rE5NINZ02JdfsTjpIUGY8W/ga/Y5JWrmu20RsSYtnV4sUgs7WTd3bDDSRPo6kCrIZHT0RzgQAeehl/vHDrLStPrHtw86/eS4rynNq3EjdNYxiticLJTScyoMPN9Fiq2OxSyOrXEhDDu1XRB4mVTRRvJH+b9hRrC+YGGJnucREqJOyynFiRMXABIqXQrwwZhmpbHEvHO4K8DMcYt8UUuJCNNu1BXFUWhPCyo+8IHvSNBVOo7qf79R1cfLVcJf0kFWGq2CnVqgEXl+SBxNaT7txiXBzAcP2wuxH7ZEMG9yjBjDlQe+qgPw2ptQ5BmVpyK+J7+0L5Pf9HIzheBAMCnwAC5cqBuDTNBX9XaQKTLeM9Ucv2uJ6yylvmER0T5HK3aBARonxREB/JJnFnBc/Jj6O9Y3/bnDLqfBObGzFYCjxQzAtIkZWvtc4RfFqlsZutP078dNml9rI7oV84un36zLRI=
  - secure: hFbu20CzN4exAtxKDkkXcxBvx+YrAdvEMNrCy+BMpPEOJL7cH3qtyk/feruAQ6kXpKHAXjhOSSJGYiknRdAsKtML7j+FolKoVCHVRfakltBgqjxPS6JTXr6XJIPWMQOgoXsZI5DFyW5mQ7UBnU3g7aDwsK5exjVsk3SghZiwyxm2gjHHY8hsJWPVz4Oy+JB5ihfp6j5CzOVcPluwBaYTRwsZM1cGG9lEcJuQr7xgwQu0OLRaWJwM93sZSuNPBK3uBbjoAPaN1FBhth4s225j/EdCpoXgVlJcDU0sQjCInCWtRW09egTKf69NoiPDMBB+CETa/MYhmlfEQgT52tJO0ZsTvR+yDBgPSH0iZ89/1eSpFwJrqXXsKzLSt56+Bt5hVHl+BBZbJZmCaqZWn6R85G+pn3HwvIsBqDLMJ0G+DJJUBMofd/t/bN9L9LFPfBXLhlr5PUAGD7lg2cTD6+yGqQsmwpvtOvXnYWMkku7STqEmmp2Lh9YAfwMQV0yVNOCTFdN1MYzM64n6chTub19/QQ1Y8LQ+dxJ+OHni4KKay9Grme8j09j31OB8M0kOkq72VYag12gurqUbrNhExTmhFNrgqlR78CD0a/1StVCZbvb577Ykb/OXX44MXJivH4XBa3YwbbDZuyy3LdreG+J+kHQBs1cyBE48bImaVUHV0bI=
  - secure: MAwmvzGheS5OlRhJ7iI32Pkk6sQ8ML5D9Gs/72UZUcTBX+H1gYXgz8doZ65NzY9nR29CVFPTD5He/I54s3rZbHZl7a7fRocGdAnLnRe2OxNB6m/8v8kySCgTZpBxLovYG8KKLAsX2LOnyNRll4H2qkTOkiCXWadHEySAFxmzEvq+bHiuM6ouecVOvBQN9cz8RduwxJk+F4JKSCzh8Dkhsr+5Dl3gQG96J0adORNnNDpp4XJU83PO6ebP4Ebg/DAlNY9Os/fVtMFzw+PKnCzLizFy5lpK5dg/pqCD4zXAWJ1x0dq1oKIAbV1PFeJzw2nE/rC0+eVbqy66Q6oG4jPLdg4ANavToIdjI8Y2JXJyP1G170a31UMwVjRgoL54JO7rU0bfPrnkKDQoTPW2sXfcB7TkRHSaD1s3MT5M0DVue1X8GXjo9m4z/E7nrSrGEXuFazV46vOes4zx4/fhdGCbi0qIFmuyjdBXPIpFe26L5qxPQxufi+J6qUR0IMtML/5jopg/GJFBKeeMGJohLQ6/KaOtBVvl4u/pXmMg6gmy0PGHCZRUc2HAxPXTpctzMp6Ts33ALhuLZXWgpoJHuBzeKFqxv8Y00wEpGimliG8iwAThb5FLyJQane4nE6St3NCPlO3ZfiDVfY1QvTPCxE6y7XVZoQnPdtxHmERpoAcygN0=
  - secure: Q8Q6doT1KFG7FbHRzOkh7oI8cnARkKixdFfMcqn3XOvC8H2nxPMFPaCt9mr1Ti70PMHkKCxN/6/9w6FoUW1GELDF/yWOKfwUt9poovNJasazRt61fTmasvshWgX3wL6OaLv2MF0HWXU5LD+CNQUxFG9R4PwE0/3sPG3psXy++gjyhtVg8lJtFvOeEYc90c2VOd5Estmdxrs2ldBO1BTH6+oR0SgDmp7VF5vKAXXK5I/Pruu/7fChBSlmFiHpHA06RlUwW3DT5hwpZSdgM/3LhAFjlQYMah0U4M3pXr8mSXf9FcQti4EF3r2ws+IniMIJrwDezd9UcGY8vbu4G56OAHR6b2QuPpOUVhlgokmFY+9PnOMHK+bxxxmr3gFwnylPbqPsl620pX6U2vJFNIeHQuJVn6fGjn9xypHZst3zm+HCoF3vfmw1UlsUHgayGHsVmJQIjm4dosgA9YBqejzrU7LYkJQAKy9kXgfsd2J1mcOxUfvMb7J/5rnLLxveBJPYzmMtSSbkHEpGUuYuakP5ylEBlfsq/dMUyGKy9Y/BEZRqK8pt3hDycENLpss/Brdnm/wtXd7ReB8Rhe1GBIl6vn7zdaN/tlR2LHAn3XMc1MphlB1BZvzndTeLsqXgapEjVyj+qrR61WZC5BGUFl45QSzoxDJjpLz/+9rXS7wUZ50=
matrix:
  fast_finish: true
  include:
  - os: linux
    language: node_js
    node_js: '8'
    after_success:
    - yarn global add meshblu-connector-schema-generator meshblu-connector-uploader-github
    - mkdir -p ./deploy/assets
    - meshblu-connector-schema-generator > ./deploy/assets/schemas.json
    - meshblu-connector-uploader-github --installers-path ./deploy/assets
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-armv7
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        --env AWS_REGION=$AWS_REGION \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        octoblu/meshblu-connector-builder:linux-armv7 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
            && upload-deb-s3 \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x86
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        --env AWS_REGION=$AWS_REGION \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        octoblu/meshblu-connector-builder:linux-x86 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
            && upload-deb-s3 \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x64
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        --env AWS_REGION=$AWS_REGION \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        octoblu/meshblu-connector-builder:linux-x64 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
            && upload-deb-s3 \
          '
  - os: osx
    node_js: '8'
    language: node_js
    after_success:
    - yarn global add meshblu-connector-pkger meshblu-connector-installer-macos meshblu-connector-uploader-github
    - meshblu-connector-pkger && meshblu-connector-installer-macos && meshblu-connector-uploader-github
